POST http://localhost:3000/api/articles/ HTTP/1.1
content-type: application/json

  {
    "title": "aaa Самый лучший музыкальный альбом этого года",
    "announce": "  Достичь успеха помогут ежедневные повторения.   Первая большая ёлка была установлена только в 1938 году.   Собрать камни бесконечности легко, если вы прирожденный герой.   Человеческие языки позволяют комбинировать слова великим множеством способов",
    "fullText": "  Освоить вёрстку несложно. Возьмите книгу новую книгу и закрепите все упражнения на практике.   Это один из лучших рок-музыкантов.   Ёлки — это не просто красивое дерево. Это прочная древесина.   Как начать действовать? Для начала просто соберитесь.   Помните, небольшое количество ежедневных упражнений лучше, чем один раз, но много.   Вы можете достичь всего. Стоит только немного постараться и запастись книгами.   Рок-музыка всегда ассоциировалась с протестами. Так ли это на самом деле?",
    "category": [
      "  Деревья",
      "  IT",
      "  Программирование",
      "  Домино",
      "  Железо",
      "  Кино",
      "  Гастроном",
      "  Без рамки",
      "  Вкусно",
      "  За жизнь"
    ],
    "comments": [
      {
        "id": "cELg3M",
        "text": "Давно не пользуюсь стационарными компьютерами. Ноутбуки победили.,Хочу такую же футболку :-),Совсем немного...,"
      },
      {
        "id": "SDePOR",
        "text": ""
      },
      {
        "id": "oKjkN5",
        "text": "Совсем немного...,Мне не нравится ваш стиль. Ощущение, что вы меня поучаете.,Мне кажется или я уже читал это где-то?,Хочу такую же футболку :-),Давно не пользуюсь стационарными компьютерами. Ноутбуки победили.,"
      },
      {
        "id": "U1XL_m",
        "text": "Плюсую, но слишком много буквы!,"
      },
      {
        "id": "z8IhKx",
        "text": "Плюсую, но слишком много буквы!,"
      }
    ]
  }

